# Generated by Django 5.0 on 2023-12-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
