# Generated by Django 5.0 on 2023-12-31 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_purchase_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="quantity",
            new_name="c",
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="sale.product"
            ),
        ),
    ]
