# Generated by Django 5.0 on 2023-12-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_rename_quantity_purchase_c_alter_stock_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="c",
            new_name="quantity",
        ),
    ]
